# Move to directory containing auction_portal_project and auction_web_project
# docker compose up --build
services:
  backend:
    build:
      context: ./auction_portal_project
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=sqlite:///auction_portal0.db
    volumes:
      - ./auction_portal_project:/app
      - ./sqlite_data/:/app/data/
    depends_on:
      - sqlite

  frontend:
    build:
      context: ./auction_web_project
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./auction_web_project:/app
      - /app/node_modules
    stdin_open: true  # Required for live reload
    tty: true  # Required for live reload

  sqlite:
    image: nouchka/sqlite3:latest
    container_name: sqlite
    volumes:
      - ./sqlite_data/:/data/
    stdin_open: true
    tty: true
    ports:
      - "9000:9000"  # Optional: Expose port for debugging, e.g., using SQLite Web (requires additional setup)

